### ISSUE TITLE
굿 :D

### ISSUE THREAD

**Issue by sigmadream** [barcelona123456/ks-web#1]
수고했습니다.

**Comment by barcelona123456** [comment]
Caused by: org.hibernate.AnnotationException: No identifier specified for entity: com.younghun.app.entity.SocialMedia

Execution failed for task ':AppApplication.main()'.
> Process 'command 'C:/Work/jdk-14/bin/java.exe'' finished with non-zero exit value 1

기본 바탕까지는 잘나오게했고 일단 소셜미디어 객체만드는거 먼저 하고있는데 저런 에러가떠서 실행이 안되는데 이유가 뭔지 잘모르겠습니다.

**Comment by barcelona123456** [comment]
해결했습니다^^

**Comment by sigmadream** [comment]
오늘 회사일 때문에 답장인 늦었는데, @Id 관련 문제 잘 해결했다니 다행입니다.

즐거운 하루 되세요!
